name: Notify Slack on Push

on:
  push:
    branches:
      - master  # or your desired branch

jobs:
  slackNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":rocket: Code pushed to *${{ github.repository }}* on branch *${{ github.ref }}* by *${{ github.actor }}*."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
